accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('post', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/(<username>)', views.UserPost.as_view(), name='for_user'),
    # path(r'by/(?P<username>[-\W]+)/(?P<pk>\d+)/$', views.PostDetail.as_view(), name='single'),
    path('by/<username>/<pk>/', views.PostDetail.as_view(), name='single'),
    path('delete/(<pk>)', views.DeletePost.as_view(), name='delete'),
]

social/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('groups/', include('groups.urls', namespace='groups')),
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Social</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity=pyth"sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'social/css/master.css' %}">

</head>
<body>
{% include 'navbar.html' %}
<div class="mycontent">
    {% block content %}


    {% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
    <div class=" jumbotron text-center" id="homepageBanner">
        <div class="container" id="textBanner">
            <h1>Welcome to Star Social!</h1>
        </div>
    </div>

{% endblock %}

templates/navbar.html
<nav class=" navbar navbar-expand-sm bg-primary  mynav " role="navigation" id="navbar">
    <div class="container">
        <ul class="nav  justify-content-end nav-pills   ">
            <a class=" mynav navbar-brand text-white " href="{% url 'home' %}">Star Social</a>
            {% if user.is_authenticated %}
                <li class="nav-item "><a class="nav-link text-white " href="{% url 'posts:create' %}">Create Post</a></li>
                <li class="nav-item "><a class="nav-link text-white " href="{% url 'posts:all' %}"> Posts</a></li>
                <li class="nav-item"><a class="nav-link text-white " href="{% url 'groups:all' %}">Groups</a></li>
                <li class="nav-item"><a class="nav-link text-white " href="{% url 'groups:create' %}">Create Group</a>
                </li>
                <li class="nav-item"><a class="nav-link text-white " href="{% url 'accounts:logout' %}">Log Out</a></li>
            {% else %}
                <li class="nav-item"><a class="nav-link text-white " href="{% url 'accounts:login' %}">Log in</a></li>
                <li class="nav-item"><a class="nav-link text-white " href="{% url 'accounts:signup' %}">Sign Up</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

templates/test.html
{% extends 'base.html' %}
{% block content %}
    <div class="jumbotron" id="homepageBanner">
        <h1 id="textBanner">You are now logged in!</h1>
    </div>
{% endblock %}

templates/thanks.html
{% extends 'base.html' %}
{% block content %}
    <div class="jumbotron" id="homepageBanner">
        <h1 id="textBanner">Thanks for visiting, come back soon!</h1>
    </div>
{% endblock %}